/**
 * Portfolio content — edit titles, copy, contact, and image assignments here.
 * Images live in images/portfolio/ (copied from Lightroom edited portfolio images).
 * Display is lowercase site-wide; keep source text lowercase for consistency.
 */
const IMG = (file) =>
  `images/portfolio/${encodeURIComponent(file).replace(/%2F/gi, "/")}`;

window.PORTFOLIO = {
  name: "maria egorova",
  role: "multidisciplinary graphic designer",
  about:
    "designer working across editorial design, book arts, and visual storytelling. interested in how form holds memory — and how the page becomes a place where history and the present meet.",
  contact: {
    email: "mariiaegorova55@gmail.com",
    location: "toronto, on",
  },
  socials: [
    { label: "instagram", href: "https://www.instagram.com/mdesigning_/" },
    { label: "linkedin", href: "https://www.linkedin.com/in/maria-egorova-300b55328/" },
  ],
  projects: [
    {
      id: "my-reading-in-a-week",
      section: "works",
      title: "my reading in a week",
      year: "2024",
      tags: ["information design", "booklet", "poster"],
      summary:
        "a personal data portrait of reading habits — expressive marks, booklet and poster.",
      description: [
        "the visual language of this project is defined by very simple, modern, and clean-looking elements. the project prioritizes expressive and abstract visualization of the reading data i gathered, using abstract elements such as lines and circles to help decode the information. the story of my reading habits is encoded in blooming leaves that stem from a main branch, with each leaf representing one reading session. i chose to create a booklet because it supports my theme of reading. i also created a poster as an addition to the booklet to create a more whole experience for viewers, allowing space for the data to be both explored more closely and understood at a glance. for the poster, the data points from each day (each stem) are organized in a circular shape, reminiscent of flowers blooming.",
        "the colour palette of greens and pinks evokes the emotions of nature and greenery, supporting the symbolism of reading as a process of growth and learning. the colours progress from light green to darker maroons to signify increased reading time, mimicking how flowers come to full bloom as they transform from green to red. the light grey backdrop for both the booklet and the poster symbolizes the feel of old books and creates a more natural tone compared to white paper, evoking a sense of calm that is often associated with reading.",
        "for my typefaces, i am using neue haas grotesk display pro for titles and new kansas for subtitles and body text. the two fonts complement each other through their high x-height and contrasting features. neue haas grotesk reinforces a modern visual style that prioritizes clarity and readability, while new kansas contributes a more old, vintage, and whimsical aesthetic that directly correlates to reading. i chose to use lowercase for titles to create a smoother reading flow without the visual interruption of capital letters, resulting in a softer, more natural, and clean look. furthermore, the lowercase titles and subtitles help the project feel more journal-esque and handcrafted, reinforcing the personalized story reflected through the data.",
        "in both the poster and the booklet, the layout emphasizes openness through the use of negative space. this allows the visual elements to breathe, enhances clarity, and creates a sense of calm and serenity, guiding the viewer’s eye naturally through the information. a spread including photographs of the environments where i read adds an extra level of customization and makes the booklet feel more personal.",
        "to bind the booklet, i used a saddle stitch. the threaded binding adds an additional personal touch and reinforces the sense of a handcrafted, individualized experience.",
        "the visualization represents the circumstances in which i read best and remains open to interpretation, encouraging the viewer to engage with and study the information to draw their own conclusions.",
        "this project made me realize that reading is not a static activity for me but rather a fluid journey that depends on my routine and surroundings. i learned for myself that i do read the best when i am at home and alone. at the same time, i discovered that i can still read a lot in public but have to be very immersed in the story with no distractions around me such as my friends. i also learned that depending on how tired i am impacts greatly how was i read; even though i pushed myself to read because it was a relaxing activity for me, in moments when i was really tired, the speed at which i read would slow down which made me feel bad about how slow i am reading. now i realize i am not a slow reader but rather my routine, external environment and my mental state all contribute to how fast and effectively i read.",
      ],
      staticImage: IMG("Scan (5).jpg"),
      motionImages: [
        IMG("2Q8A8071.jpg"),
        IMG("2Q8A8106.jpg"),
        IMG("Scan 2 (3).jpg"),
        IMG("Scan 3 (4).jpg"),
        IMG("Scan 4 (4).jpg"),
        IMG("Scan 5 (7).jpg"),
        IMG("Scan 6 (2).jpg"),
        IMG("Scan 7 (3).jpg"),
      ],
      gallery: [
        IMG("Scan (5).jpg"),
        IMG("2Q8A8071.jpg"),
        IMG("2Q8A8106.jpg"),
        IMG("Scan 2 (3).jpg"),
        IMG("Scan 3 (4).jpg"),
        IMG("Scan 4 (4).jpg"),
        IMG("Scan 5 (7).jpg"),
        IMG("Scan 6 (2).jpg"),
        IMG("Scan 7 (3).jpg"),
        IMG("Scan 8 (3).jpg"),
        IMG("Scan 8 (3)-2.jpg"),
        IMG("Scan 9 (6).jpg"),
        IMG("Scan 10 (4).jpg"),
        IMG("Scan 11 (2).jpg"),
        IMG("Scan 12-2.jpg"),
        IMG("Scan 14 (1).jpg"),
      ],
    },
    {
      id: "reconstruction-from-memory",
      section: "works",
      title: "reconstruction from memory",
      year: "2024",
      tags: ["book design", "poetry", "editorial"],
      summary:
        "a bilingual poetry collection — russian and english, autumn light, memory and identity.",
      description: [
        "“reconstruction from memory” is a poetry collection book that spotlights russian poetry. the book is bilingual, containing passages in both english and russian.",
        "the poems incorporated in this book are autumn themed, correlating to the fall imagery while also having a deeper emotional connection of fall being the time of reminiscence and nostalgia. the theme of memories and their fleeting and often fickle nature is symbolic of the autumn leaves falling down every year, and getting lost and forgotten with time. the book is a personal reflection on past and an exploration of the russian part of my identity and what it means to me.",
        "the book is completed in warm tones to reflect the fall season and create a vintage and soft, comfortable feeling.",
        "the coloured paper used for poetry exerpt pages reflects the texture of a leaf. furthermore, the warm toned yellows, oranges and browns colours of the paper connect back to the fall imagery of the book.",
      ],
      staticImage: IMG("Scan 13.jpg"),
      motionImages: [
        IMG("Scan 13-2.jpg"),
        IMG("Scan 27.jpg"),
        IMG("Scan 35.jpg"),
        IMG("Scan 15.jpg"),
        IMG("Scan 16.jpg"),
        IMG("Scan 39.jpg"),
        IMG("Scan 22.jpg"),
        IMG("Scan 28.jpg"),
        IMG("Scan 36.jpg"),
      ],
      gallery: [
        IMG("Scan 13.jpg"),
        IMG("Scan 13-2.jpg"),
        IMG("Scan 27.jpg"),
        IMG("Scan 28.jpg"),
        IMG("Scan 15.jpg"),
        IMG("Scan 16.jpg"),
        IMG("Scan 35.jpg"),
        IMG("Scan 36.jpg"),
        IMG("Scan 39.jpg"),
        IMG("Scan 22.jpg"),
        IMG("Scan 40.jpg"),
        IMG("Scan 30.jpg"),
        IMG("Scan 31.jpg"),
        IMG("Scan 32.jpg"),
        IMG("Scan 34.jpg"),
        IMG("Scan 37.jpg"),
        IMG("Scan 43.jpg"),
        IMG("Scan 44.jpg"),
        IMG("Scan 45.jpg"),
        IMG("Scan 46.jpg"),
        IMG("Scan 47.jpg"),
        IMG("Scan 17.jpg"),
        IMG("Scan 18.jpg"),
        IMG("Scan 19.jpg"),
        IMG("Scan 23.jpg"),
        IMG("Scan 24.jpg"),
        IMG("Scan 25.jpg"),
        IMG("Scan 26.jpg"),
        IMG("Scan 14.jpg"),
      ],
    },
    {
      id: "editorial-studies",
      section: "works",
      title: "the sound and the story / greenland unicorns",
      year: "2024",
      tags: ["magazine", "typography", "layout"],
      summary:
        "magazine essay layouts — orange for paradise lost, pink for the alicorn, type as structure.",
      description: [
        "for “the sound and the story exploring the world of paradise lost” essay i chose to use orange as my accent colour to draw attention to importnat elements of the text and also convey warmth of milton’s poetic language in the original work. the vibrancy of orange helps to reflect the dynamic relationship between sound and narrative that pullman emphasizes in his analysis.",
        "for natalie lawrence’s “greenland unicorns and the magical alicorn” essay, i chose to use pink as an additional colour. i chose pink to reflect people’s whimsical perception of these mythical creatures. pink is a very soft colour, often associated with childhood which further helps to reinforce the magical tone lawrence maintains in her essay. the colour helps communicate enchantment described in the essay.",
        "both opening spreads are done in full colour to engage the reader and grab their attention. as observed during my reserach, many magazine stories start off bold and loud to “hook” the reader and then slowly set into the flow of the story which i tried to mirror through the boldness of my first pages. the colours and typeface pairings further complement the distinct themes of the two essays.",
        "for my main body text i chose to use new kansas. new kansas is a contemporary serif typeface. the typeface is a reinterpretation of the cooper typeface and was redesigned in 2020 by miles newlyn; new kansas is a blend of vintage coziness with a touch of modernity. the letterforms of the typeface are highly legible while staying distinctive and unique. the serif typeface conveys a humanist quality through its gentle curves and slab serifs. furthermore, the typeface comes in various different weights and styles which is highly useful when designing a magazine issue to distinguish different type of content such as footnotes, subtitles and etc.",
      ],
      staticImage: IMG("Scan 50.jpg"),
      motionImages: [
        IMG("Scan 48.jpg"),
        IMG("Scan 12.jpg"),
        IMG("Scan 51.jpg"),
        IMG("Scan 52.jpg"),
        IMG("Scan 64.jpg"),
        IMG("Scan 56.jpg"),
      ],
      gallery: [
        IMG("Scan 50.jpg"),
        IMG("Scan 48.jpg"),
        IMG("Scan 12.jpg"),
        IMG("Scan 51.jpg"),
        IMG("Scan 52.jpg"),
        IMG("Scan 54.jpg"),
        IMG("Scan 56.jpg"),
        IMG("Scan 57.jpg"),
        IMG("Scan 64.jpg"),
        IMG("Scan 65.jpg"),
        IMG("Scan 66.jpg"),
        IMG("Scan 67.jpg"),
      ],
    },
  ],
};
